// This example uses Jenkin's "declarative" syntax
//This file points to the other repo that has the code from the textbook using gradle 

pipeline {
  agent {
    kubernetes {
      // Define the pod template directly within the kubernetes agent
      containerTemplate {
        name 'gradle'
        image 'gradle:latest'
        command 'sleep'
        args '30d'
      }
    }
  }

  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/bufferbox/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
        sh """
          chmod +x gradlew
        """
      }
    }

    stage('jacocoTestCoverageVerification') {
	   when {
	       branch "main"
	   }
	      steps {
		sh """
		  ./gradlew test
		  ./gradlew jacocoTestCoverageVerification
		"""  
	      }
    }
	
	stage('JaCoCo checkstyle test') {
	  when {
	         not branch "main"
		   //not { branch 'main' }	
	   }
	    steps {
		    sh """
	         
	          ./gradlew jacocoTestReport
	          ./gradlew checkstyleMain
	        """
	        publishHTML (target: [
	          reportDir: 'build/reports/checkstyle',
	          reportFiles: 'main.html',
	          reportName: "JaCoCo Checkstyle"
	        ]) 
		  }	
	}	
  }
   post {
    always {
      echo 'pipeline complete.'
    }
    success {
      echo 'tests pass!'
    }
    failure {
      echo 'tests fail!'
    }
  }
}
